# Generated by Django 2.2.2 on 2019-06-27 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190627_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app.Team'),
        ),
    ]
