# Generated by Django 2.2.2 on 2019-06-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190628_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
