# Generated by Django 2.2.2 on 2019-06-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190628_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_placeholder',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_placeholder',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
