# Generated by Django 2.2.2 on 2019-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190628_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
